DROP DATABASE IF EXISTS Bodegas;

CREATE database Bodegas;

USE Bodegas;

-- TABLAS PADRES

-- Tabla Bodegas
CREATE TABLE BODEGAS (
   IDBODEGAS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   IDEMPLEADOS INT NOT NULL,
   NOMBRE VARCHAR (100) NOT NULL,
   UBICACION VARCHAR (100) NOT NULL,
   TELEFONO VARCHAR (100) NOT NULL,
   EMAIL VARCHAR (100) NOT NULL UNIQUE
);

-- Tabla Proveedores
CREATE TABLE PROVEEDORES (
    IDPROVEEDORES INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBREPROVEEDOR VARCHAR (100) NOT NULL,
    TELEFONO VARCHAR (100) NOT NULL,
    UBICACION VARCHAR (100) NOT NULL,
    TARIFA INT NOT NULL,
    EMAIL VARCHAR (100) NOT NULL UNIQUE
);

-- Tabla Clientes
CREATE TABLE CLIENTES (
    IDCLIENTES INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (100) NOT NULL,
    REFERENCIA VARCHAR (100) NOT NULL,
    TELEFONO VARCHAR (200) NOT NULL,
    EMAIL VARCHAR (100) NOT NULL UNIQUE
);

-- Tabla Categoria
CREATE TABLE CATEGORIA_VINOS (
   IDCATEGORIA_VINOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   IDVINOS INT NOT NULL
   NOMBRE VARCHAR (100) NOT NULL,
   DESCRIPCION VARCHAR (100) NOT NULL
);


-- TABLAS CON REFERENCIA FK
-- Tabla De Vinos
CREATE TABLE VINOS (
   IDVINOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   IDBODEGAS INT NOT NULL,
   NOMBRE VARCHAR (100) NOT NULL,
   VARIEDAD VARCHAR (100) NOT NULL,
   ANIO INT NOT NULL,
   PRECIO INT NOT NULL,
   CANTIDAD INT NOT NULL,
   IDCATEGORIA_VINOS INT NOT NULL
);



-- Tabla Empleados

CREATE TABLE EMPLEADOS (
   IDEMPLEADOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   IDBODEGAS INT NOT NULL,
   NOMBRE VARCHAR (100) NOT NULL,
   PUESTO VARCHAR (100) NOT NULL,
   EMAIL VARCHAR (100) NOT NULL UNIQUE,
   TELEFONO VARCHAR (100) NOT NULL,
   FECHA_INGRESO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Promociones
CREATE TABLE PROMOCIONES (
   IDPROMOCIONES INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   IDVINOS INT NOT NULL,
   NOMBRE VARCHAR (100) NOT NULL,
   DESCRIPCION VARCHAR (100) NOT NULL,
   FECHA_INICIO DATETIME DEFAULT CURRENT_TIMESTAMP,
   FECHA_FIN VARCHAR (100) NOT NULL,
   DESCUENTO VARCHAR (100) NOT NULL
);


-- Tabla De Ventas
CREATE TABLE VENTAS (
   IDVENTAS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   IDCLIENTES INT NOT NULL,
   IDVINOS INT NOT NULL,
   IDBODEGAS INT NOT NULL
   CANTIDAD INT NOT NULL,
   PRECIO_TOTAL VARCHAR (100) NOT NULL,
   FECHA DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- FOREING KEYS


ALTER TABLE VINOS
  ADD CONSTRAINT FK_VINOS_BODEGAS
  FOREIGN KEY (IDBODEGAS) REFERENCES BODEGAS (IDBODEGAS);

ALTER TABLE VINOS
  ADD CONSTRAINT FK_VINOS_BODEGAS_CAT
  FOREIGN KEY (IDCATEGORIA_VINOS) REFERENCES CATEGORIA_VINOS (IDCATEGORIA_VINOS);


ALTER TABLE EMPLEADOS
  ADD CONSTRAINT FK_EMPLEADOS_BODEGAS
  FOREIGN KEY (IDBODEGAS) REFERENCES BODEGAS (IDBODEGAS);

ALTER TABLE PROMOCIONES
ADD CONSTRAINT FK_PROMOCIONES_VINOS
FOREIGN KEY (IDVINOS) REFERENCES VINOS (IDVINOS);


ALTER TABLE VENTAS
  ADD CONSTRAINT FK_VENTAS_CLIENTES
  FOREIGN KEY (IDCLIENTES) REFERENCES CLIENTES (IDCLIENTES);
  
ALTER TABLE VENTAS
  ADD CONSTRAINT FK_VENTAS_VINOS
  FOREIGN KEY (IDVINOS) REFERENCES VINOS (IDVINOS);