USE Bodegas;

SET GLOBAL local_infile = true;

LOAD DATA LOCAL INFILE '/sql_project/sql_project/Data.csv/BODEGAS.csv'
INTO TABLE AREAS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(IDBODEGAS, IDEMPLEADOS, NOMBRE, UBICACION, TELEFONO, EMAIL);

LOAD DATA LOCAL INFILE '/sql_project/sql_project/Data.csv/CATEGORIA_VINOS.csv'
INTO TABLE AREAS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(IDCATEGORIA_VINOS, VINO, NOMBRE, DESCRIPCION);

LOAD DATA LOCAL INFILE '/sql_project/sql_project/Data.csv/CLIENTES.csv'
INTO TABLE AREAS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(IDCLIENTES, NOMBRE, REFERENCIA, TELEFONO, EMAIL);

LOAD DATA LOCAL INFILE '/sql_project/sql_project/Data.csv/EMPLEADOS.csv'
INTO TABLE AREAS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(IDEMPLEADOS, IDBODEGAS, NOMBRE, PUESTO, EMAIL, TELEFONO, FECHA_INGRESO);

LOAD DATA LOCAL INFILE '/sql_project/sql_project/Data.csv/PROMOCIONES.csv'
INTO TABLE AREAS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(IDPROMOCIONES, IDVINOS, NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, DESCUENTO);

LOAD DATA LOCAL INFILE '/sql_project/sql_project/Data.csv/PROVEEDORES.csv'
INTO TABLE AREAS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(IDPROVEEDORES, NOMBREPROVEEDOR, TELEFONO, UBICACION, TARIFA, EMAIL);

LOAD DATA LOCAL INFILE '/sql_project/sql_project/Data.csv/VENTAS.csv'
INTO TABLE AREAS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(IDVENTAS, IDCLIENTES, IDVINOS, IDBODEGAS, CANTIDAD, PRECIO_TOTAL, FECHA);

LOAD DATA LOCAL INFILE '/sql_project/sql_project/Data.csv/VINOS.csv'
INTO TABLE AREAS
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(IDVINOS, IDBODEGAS, NOMBRE, VARIEDAD, ANIO, PRECIO, CANTIDAD, IDCATEGORIA_VINOS);